name: Assign IDs

on:
  push:
    branches: main

permissions: {}

jobs:
  assign-ids:
    name: Assign IDs
    runs-on: ubuntu-latest
    permissions:
      contents: write # for create-pull-request
      pull-requests: write # for create-pull-request
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Cache cargo bin
        id: admin-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Assign IDs
        id: assign
        run: |
          message=$(rustsec-admin assign-id --github-actions-output)
          echo "commit_message=${message}" >> $GITHUB_OUTPUT

      - name: Create duplicate ID assignment guard
        run: |
          echo "This file causes merge conflicts if two ID assignment jobs run concurrently." > .duplicate-id-guard
          echo "This prevents duplicate ID assignment due to a race between those jobs." >> .duplicate-id-guard
          ls -R ./crates/ ./rust/ | sha256sum >> .duplicate-id-guard

      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.assign.outputs.commit_message }}
          title: ${{ steps.assign.outputs.commit_message }}
          branch: assign-ids
