name: Validate

on:
  pull_request: {}
  push:
    branches: main

permissions: {}

jobs:
  lint:
    name: Lint advisories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Cache cargo bin
        id: admin-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cargo/bin
          key: rustsec-admin-4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Install rustsec-admin
        if: steps.admin-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/rustsec/rustsec rustsec-admin --rev 4f949d61d9ed2ef59f8c4448b5ab96e6eef0d6ed

      - name: Lint advisories
        run: rustsec-admin lint --skip-namecheck rustdecimal,vec-const
